minPlayer: 2
pregameCountdown: 60
#in seconds
gameClock: 10
#in minutes
messagePrefix: "&8[&bTrench&8] &c"
#to be used for broudcasting and messing players
spawn:
   world: "TrenchWarfare"
   x: 602
   y: 76
   z: 68
red:
   world: "TrenchWarfare"
   x: 514
   y: 64
   z: 89
blue:
   world: "TrenchWarfare"
   x: 689
   y: 64
   z: 117
mapBounderies:
   minX: 511
   maxX: 692
   minZ: 86
   maxZ: 120
trenchLocation:
   red: 592
   blue: 611
flag:
   red:
     x: 554
     y: 60
     z: 100
   blue:
     x: 649
     y: 60
     z: 106
fort:
   red: 534
   blue: 669
