minPlayer: 2
pregameCountdown: 60
#in seconds
gameClock: 10
#in minutes
messagePrefix: "&8[&bTrench&8] &c"
#to be used for broudcasting and messing players
spawn:
   world: "TrenchWarfare"
   x: 601
   y: 76
   z: 68
red:
   world: "TrenchWarfare"
   x: 514
   y: 64
   z: 89
blue:
   world: "TrenchWarfare"
   x: 689
   y: 64
   z: 117
mapBounderies:
   minX: 511
   maxX: 692
   minZ: 86
   maxZ: 120
