minPlayer: 2
pregameCountdown: 20
#in seconds
gameClock: 5
#in minutes
messagePrefix: "&8[&bTrench&8] &c"
#to be used for broudcasting and messing players
spawn:
   world: "TrenchWarfare"
   x: 602
   y: 64
   z: 70
red:
   world: "TrenchWarfare"
   x: 514
   y: 64
   z: 89
blue:
   world: "TrenchWarfare"
   x: 689
   y: 64
   z: 117
